# Generated by Django 4.1 on 2024-04-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("self", models.URLField(max_length=2048)),
                ("related", models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("twitter", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="json_api.person",
                    ),
                ),
                (
                    "links",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="json_api.link"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="json_api.article",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="json_api.comment",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "comment")},
            },
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="json_api.person"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="comments",
            field=models.ManyToManyField(
                through="json_api.ArticleComment", to="json_api.comment"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="links",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="json_api.link"
            ),
        ),
    ]
